# Generated by Django 3.2.14 on 2022-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('albumart', models.ImageField(default='', max_length=255, upload_to='media/%Y/%m/%d')),
                ('mediafile', models.FileField(default='', max_length=255, upload_to='media/')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order',)},
            },
        ),
    ]
